package com.jetbrains.micropython.nova.real

internal const val LOREM_IPSUM =
    """
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam urna diam, pharetra sodales hendrerit nec, elementum ut justo. Sed vitae turpis quis tortor dignissim pharetra. Vivamus magna dolor, varius vitae convallis ac, maximus et neque. Sed rhoncus, odio a ullamcorper cursus, eros mauris maximus dui, non convallis libero nisl vitae eros. Pellentesque nec tincidunt lectus, vitae viverra nunc. Sed porttitor augue in ex sollicitudin, vel efficitur ex eleifend. Quisque ut mollis dui. Fusce fermentum ligula metus, sed dapibus lectus finibus vel.

Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Duis quam turpis, aliquam et feugiat eu, tristique vel leo. Fusce sagittis vehicula tortor, in pulvinar diam molestie id. Nam id sagittis felis. Donec odio enim, auctor vitae volutpat id, euismod id ligula. Vestibulum ipsum nulla, rutrum at lorem vitae, lacinia sollicitudin libero. Aenean neque mi, auctor eget aliquam vitae, interdum id enim. Nam lorem metus, scelerisque sed feugiat a, consequat quis velit.

Proin imperdiet lobortis sagittis. In dui orci, vestibulum id finibus facilisis, varius eu elit. Donec tempus consectetur nulla vitae sollicitudin. Maecenas eleifend volutpat diam eget tempus. Fusce laoreet sed neque vitae interdum. Morbi sit amet vestibulum urna, dignissim maximus nunc. Sed varius enim in purus posuere bibendum. Curabitur id commodo lacus. Ut turpis metus, gravida a lectus at, tempus viverra augue. Sed pulvinar ornare accumsan. Suspendisse feugiat placerat tortor, a placerat nulla imperdiet eu. Etiam tempor efficitur erat eget varius. Proin sed nulla sed est lobortis vehicula.

Nulla facilisi. Curabitur ut sagittis elit. Quisque magna urna, posuere at augue eget, egestas egestas purus. Nullam aliquam, augue in commodo venenatis, sem purus commodo lorem, et tincidunt libero quam vitae erat. Aenean et est sagittis, accumsan magna at, luctus sem. Maecenas placerat enim eu quam sollicitudin, non blandit felis sollicitudin. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.

Etiam at volutpat elit. Cras commodo, arcu id semper posuere, ipsum est ullamcorper elit, vel eleifend nibh elit vitae justo. Cras vitae quam a dui fringilla pharetra. Pellentesque a velit nec metus maximus ullamcorper at vitae orci. Fusce pellentesque sollicitudin quam sit amet vehicula. Nunc dictum, ipsum sit amet varius feugiat, dui massa facilisis felis, quis dapibus tellus dui vel neque. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Phasellus sed semper orci. Donec et nisl ut justo efficitur bibendum.

Phasellus lorem sapien, mattis quis nisl pretium, dapibus faucibus augue. Fusce quis volutpat enim. Vestibulum viverra nunc gravida viverra mollis. Aliquam quis consequat diam. Curabitur scelerisque nec massa et consectetur. Aliquam at arcu non massa bibendum venenatis sed ut dolor. Donec nec tellus consectetur, faucibus mi congue, tincidunt magna. Nam lobortis fringilla velit vitae pellentesque. Nulla varius pellentesque ante eget viverra.

Etiam egestas varius arcu id facilisis. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. In consequat nulla ut vehicula pharetra. Duis in vulputate odio. Suspendisse potenti. Aliquam ornare rutrum accumsan. Etiam nec nunc tellus. Morbi vitae laoreet neque, vitae lobortis diam. Fusce vel orci quis justo porta fringilla sit amet eu justo. Nullam accumsan accumsan libero. Suspendisse luctus elit mi, id sodales velit iaculis vitae. Donec feugiat lectus eros, at sollicitudin urna dignissim non.

Duis diam tellus, imperdiet eu finibus non, facilisis non sem. Donec eu feugiat odio. Morbi lectus dui, accumsan sed congue a, vestibulum luctus dolor. Phasellus bibendum lacus nec nisl sagittis egestas. Aenean eget eleifend arcu, quis auctor justo. Nam at imperdiet tellus. Nulla tempus lobortis quam eget aliquet. Proin sit amet orci gravida, ultrices leo vitae, auctor nisl. Cras sodales pretium imperdiet. Aenean scelerisque faucibus mauris eu lacinia. Vestibulum posuere est diam, non luctus sem rhoncus a.

Vivamus accumsan enim sed neque scelerisque, ut varius ante ornare. Aenean eu quam ut augue blandit laoreet. Fusce lobortis gravida diam. Aliquam facilisis lectus vel nisl congue, a eleifend quam ullamcorper. Ut laoreet suscipit luctus. Quisque tincidunt pellentesque volutpat. Morbi convallis eleifend nisl. In facilisis enim vitae rutrum commodo.

Maecenas consectetur arcu sit amet ante vehicula, in varius nisl fringilla. Sed ac sapien porta, vehicula lorem nec, sodales elit. Fusce tincidunt libero sit amet pulvinar laoreet. Maecenas pellentesque ex suscipit risus iaculis, id convallis massa pellentesque. Donec volutpat, eros et posuere euismod, mi est fringilla nunc, vel sollicitudin enim neque sit amet ex. Vivamus vitae lorem vulputate, sodales massa sed, consectetur erat. Cras vehicula magna a nisi euismod, ut pretium neque viverra. Nullam fermentum, purus eu porta mattis, tortor odio luctus velit, vitae venenatis est nunc eget lorem. Quisque eleifend mi quis ante laoreet, ornare tristique turpis dignissim. Etiam at massa quis nisl malesuada viverra at a lorem. Pellentesque nisl nisi, condimentum eget convallis sed, feugiat sit amet sem. Maecenas a nisi nibh. Sed condimentum augue tellus, id faucibus augue feugiat eu. Pellentesque sagittis congue nunc.

Duis egestas fringilla magna sit amet volutpat. Nulla vulputate quam non dolor eleifend, in pretium augue fermentum. Sed ac feugiat purus, molestie feugiat ipsum. Sed tempor dui odio, eget dictum enim fermentum ut. In hac habitasse platea dictumst. Phasellus pulvinar gravida diam non vestibulum. Donec pharetra diam elit, sit amet porta erat aliquet quis. Cras a est suscipit, iaculis ipsum at, finibus augue. Praesent sed risus varius, posuere nunc lobortis, euismod sapien. Nulla et arcu fringilla, ultricies mauris nec, consequat neque. Vivamus at est et nunc cursus feugiat. Morbi nec ante arcu.

Proin a risus tristique, pellentesque lacus id, pretium augue. Vivamus tellus nunc, porta at vestibulum eu, sagittis vel odio. Pellentesque varius ac diam sit amet molestie. Pellentesque a augue ut nisl vestibulum maximus vel a nibh. Ut velit massa, mattis sed ipsum sit amet, aliquet sodales mauris. Nulla dapibus auctor felis. Praesent at aliquet orci. Aenean feugiat facilisis vestibulum. Phasellus tempus quis est ac malesuada. Integer ac convallis mauris, a posuere turpis. Morbi nisi nulla, consectetur vel commodo vel, eleifend sed arcu. Morbi faucibus, elit non rutrum euismod, enim purus gravida augue, vel pulvinar leo nisi et turpis. Vestibulum sagittis tincidunt ligula, vitae pretium eros feugiat a. Aliquam sit amet velit id magna commodo finibus.

Sed nec mollis diam, in venenatis nisl. Integer dapibus fermentum ipsum eu venenatis. Praesent fringilla, sem ut lacinia pretium, elit mi lacinia risus, et maximus dolor massa et sem. Phasellus et ultricies lectus. Ut luctus massa et felis tincidunt, pellentesque accumsan augue varius. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. In sed magna a ante condimentum auctor. Fusce sit amet mollis sem, a dapibus diam.

Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nunc bibendum nec orci non tempus. Fusce tempor velit at magna commodo, in tincidunt arcu ullamcorper. Fusce bibendum efficitur leo, at euismod leo euismod tincidunt. Curabitur at enim ex. Suspendisse potenti. Nullam maximus accumsan nunc. Aliquam rutrum suscipit posuere. Praesent a rutrum arcu, id consectetur nulla. Sed mollis turpis a eleifend tincidunt. Ut pretium vulputate aliquam. Nullam sapien risus, convallis eget feugiat eu, vehicula in nibh. Phasellus non ex sed diam vehicula ullamcorper. Curabitur consequat porttitor consequat.

Donec ipsum urna, imperdiet non enim ut, vehicula suscipit nunc. Sed dictum enim ut scelerisque sagittis. In cursus lorem eu lorem volutpat, ac imperdiet nibh consectetur. Aenean vitae neque lorem. Phasellus vehicula mi erat, at sodales ante efficitur vel. Vivamus egestas luctus diam, sit amet lacinia sem maximus ac. Vestibulum fermentum, erat et efficitur luctus, ligula erat ornare urna, in interdum leo mauris eget eros. Morbi libero dolor, imperdiet quis porta sed, ornare ut magna. Suspendisse potenti. Sed mattis lacus sed est eleifend, tincidunt lobortis libero tristique. Maecenas egestas, massa et faucibus egestas, neque erat finibus risus, eu rhoncus neque urna sit amet ligula.

Nulla malesuada odio nisl, egestas lacinia ante porttitor eu. Sed at tortor orci. Quisque congue sapien eu condimentum tincidunt. Nunc lobortis neque eget purus imperdiet fringilla. Nulla vitae vehicula metus, vitae sagittis sapien. Nam vestibulum est in nisl commodo sagittis. Pellentesque tincidunt est ante, a mollis nisi interdum eu. Integer congue fringilla nulla, vitae consequat libero egestas vel.

Morbi dictum laoreet mauris vel fringilla. Nullam tristique vitae urna id suscipit. Aenean dui ligula, cursus sed varius vitae, luctus non diam. Donec vitae egestas sapien, eu efficitur neque. Etiam accumsan fermentum enim a luctus. Donec faucibus convallis nisi volutpat varius. Quisque ac leo laoreet, iaculis magna at, sodales nisl. Interdum et malesuada fames ac ante ipsum primis in faucibus. Maecenas tincidunt, nunc et porta semper, lectus nibh porta tortor, elementum porttitor neque sapien et massa.

Duis in lectus elit. Praesent varius elit urna, a sollicitudin sapien porttitor id. Interdum et malesuada fames ac ante ipsum primis in faucibus. Fusce ultricies mauris ut purus condimentum tincidunt. Integer gravida est quis nunc pharetra sodales. Donec dapibus congue orci bibendum scelerisque. Suspendisse facilisis cursus libero, quis sodales nisi pulvinar eu.

Nunc nisl mi, feugiat id venenatis sit amet, euismod a purus. Nulla cursus, dui quis commodo hendrerit, orci urna gravida orci, eu porta nibh sem a lectus.        
    """